install.packages('egg')
install.packages('gridExtra')
library(egg)
library(ggplot2)
library(gridExtra)
str(airquality)
MonthlyOzone<-qplot(Month,Ozone, data=airquality,color=Ozone)
DailyOzone<-qplot(Day, Ozone, data=airquality,color=Ozone)
MonthlyTemp<-qplot(Month, Temp, data=airquality, geom=c('point','smooth'),color=Temp)
DailyTemp<-qplot(Day, Temp, data=airquality, geom=c('point','smooth'),color=Temp,method='lm',se=F)
Solar<-qplot(Solar.R,data=airquality)+labs(x='SolarRay',y='Frequency')
Wind<-ggplot(airquality)+geom_bar(aes(x=Wind))
MonthlyWind<-ggplot(airquality,aes(x=Wind,y=Month))+geom_boxplot()
DailyWind<-ggplot(airquality,aes(x=Wind,y=Day))+geom_boxplot()
ggarrange(MonthlyOzone,DailyOzone,MonthlyTemp,DailyTemp,Solar,Wind,MonthlyWind,DailyWind,ncol=2,nrow=4)

